### ISSUE TITLE
Use of uninitialized value in substr at simuG.pl line 1164.

### ISSUE THREAD

**Issue by riddhideshmukh** [yjx1217/simuG#10]
I ran the following command with simuG and received the following message in execution and no output is created.

perl simuG.pl -refseq  -snp_vcf  -prefix 

[Thu Jul 21 10:12:15 2022]
Starting simuG ..

[Thu Jul 21 10:12:15 2022]
Check specified options ..
Running simuG for SNP/INDEL simulation >>
Ignore all options for CNV/inversion/translocation simulation.

This simulation use the random seed: 1864782145

The option snp_vcf has been specified: snp_vcf = <filename>
Ignore incompatible option: snp_count
Ignore incompatible option: snp_model
Ignore incompatible option: titv_ratio

[Thu Jul 21 10:12:16 2022]
Parsing the input vcf file: <filename>
Use of uninitialized value in substr at /scratch/rdeshmuk/simuG/simuG.pl line 1164.
[Thu Jul 21 12:10:13 2022]
Introducing defined SNP/INDELs based on the input vcf file(s):
> snp_vcf =<filename>

Could you tell me what the issue is and how I can solve this?

**Comment by yjx1217** [comment]
Hi riddhideshmukh，

You need to provide the expected files and expected values for those specified options (e.g. -refseq, -snp_vcf, and -prefix).
For example:

perl simuG.pl -refseq your_refseq_file.fasta -snp_vcf your_snp_vcf_file.vcf -prefix your_prefix

It is strongly recommended to go through the Quick Start section to get familiar with how it works.

Best,
Jia-Xing

**Comment by riddhideshmukh** [comment]
I have provided the files, I removed file names from my question to prevent confusion. 

This is what my command looks like 
perl simuG.pl -refseq GCF_000836215.1_genomic.fna -snp_vcf GenomeWideSNPs.recode.vcf.gz -prefix output1

**Comment by yjx1217** [comment]
Hi riddhideshmukh，

Two things to check:
1) Make sure to use the latest commited version ([16e4eea](https://github.com/yjx1217/simuG/commit/16e4eeab285e0574c1ad7ce50c5bb34274346250)) of simuG on GitHub for your test.  
2) Please check whether the chromosome ID defined in your vcf file is consistent with the reference genome file that you used in terms of naming conventions (e.g. chr1 vs 1, etc).

And if possible, you can share your testing data to me, so that I can take a closer look.

Best,
Jia-Xing

**Comment by riddhideshmukh** [comment]
Thanks Jia-Xing
It was a chromosome ID issue. I was able to get an output file.

**Comment by yjx1217** [comment]
Great！
