### ISSUE TITLE
Argument "QUAL" isn't numeric in numeric ge (>=) at simuG.pl line 815, <$fh> line 6.

### ISSUE THREAD

**Issue by mattbird567** [yjx1217/simuG#12]
Hi, 

This may be a simple fix but i am trying to create some synthetic data with pre-defined SNPs using a .vcf file. I assume my .VCF file is the problem so i have included what it looks like below (as a .txt file as i can't upload a .vcf). Please let me know if there is a specific format i need the vcf in.

Many Thanks,
Matt

[myfile.txt](https://github.com/yjx1217/simuG/files/9973176/myfile.txt)

**Comment by yjx1217** [comment]
Hi Matt,

Thanks for providing the input vcf file that you used, which is very helpful.
The error was triggered due to the lack of a leading '#' character in the vcf header line "CHROM   POS     ID      REF     ALT     QUAL    FILTER  INFO" (note that you have two such lines in your file but one of them does not start with '#').


Best,
Jia-Xing

**Comment by mattbird567** [comment]
Thanks Jia-Xing! I now have a simulated output!

**Comment by yjx1217** [comment]
Great!  :-)

I will close this thread then. 

Best,
Jia-Xing
