### ISSUE TITLE
slow CNV creation

### ISSUE THREAD

**Issue by RichardCorbett** [yjx1217/simuG#5]
Hi there,

I am giving your tool a try as it looks very simple to run and it seems to do exactly what I want for simulating CNV changes in germline nanopore reads.

I am running with this command:
```
simuG.pl -r hg38_no_alt.fa -cnv_count 50 -cnv_min_size 500 -cnv_max_size 300000000
```

But this has been running for 8 days.     Do you have any tips to make this run faster?

**Comment by yjx1217** [comment]
Hi Richard,

Thanks for trying out simuG. And yes, 8 days are way too long! 
I think this problem is likely due to  the fact that you have set the cnv_max_size too large (3Gb in your current setting). Since simuG assumes a uniform distribution when sampling cnv size, so it is highly likely to occur that the sampled CNV size is too large to be placed into any human chromosome. In this case, simuG will keep trying to find a chromosomal location to place this sampled CNV but will never succeed. To prevent this to occur, I should probably implement an internal safe bound check for simuG in future.  For now, please try to reduce the value of -cnv_max_size to a more realistic value (e.g. 1-10 Mb) and definitely make sure it is smaller than the size of the largest chromosomes of your input genome (which is ~249Mb for human genome). Let me know how it works. 

Best,
Jia-Xing
